// MongoDB seed script for Incident Engine
// Run: mongosh < mongo_seed.js
/* eslint-env mongo */
/* eslint-disable no-restricted-globals */
/* global use */

use('support_system');

db.customers.deleteMany({});
db.agents.deleteMany({});
db.incidents.deleteMany({});

db.customers.insertMany([
  {
    customer_id: 'CUST001',
    name: 'Rahul Sharma',
    dob: '1995-05-12',
    address: 'Delhi Street 21',
    mobile: '9876543210',
    email: 'rahul@gmail.com',
    location: 'Delhi',
    created_date: new Date(),
  },
  {
    customer_id: 'CUST002',
    name: 'Priya Verma',
    dob: '1993-08-22',
    address: 'Kolkata Sector 4',
    mobile: '9876543211',
    email: 'priya@gmail.com',
    location: 'Kolkata',
    created_date: new Date(),
  },
  {
    customer_id: 'CUST003',
    name: 'Amit Das',
    dob: '1990-03-10',
    address: 'Mumbai West',
    mobile: '9876543212',
    email: 'amit@gmail.com',
    location: 'Mumbai',
    created_date: new Date(),
  },
  {
    customer_id: 'CUST004',
    name: 'Neha Kapoor',
    dob: '1998-11-15',
    address: 'Bangalore Road 10',
    mobile: '9876543213',
    email: 'neha@gmail.com',
    location: 'Bangalore',
    created_date: new Date(),
  },
  {
    customer_id: 'CUST005',
    name: 'Rohit Singh',
    dob: '1994-07-01',
    address: 'Patna Central',
    mobile: '9876543214',
    email: 'rohit@gmail.com',
    location: 'Patna',
    created_date: new Date(),
  },
]);

db.agents.insertMany([
  {
    uid: 'AGT001',
    password: 'pass123',
    name: 'Ankit Singh',
    email: 'ankit@support.com',
    phone: '9001111111',
    department: 'Technical Support',
    created_date: new Date(),
  },
  {
    uid: 'AGT002',
    password: 'pass123',
    name: 'Sudeep Roy',
    email: 'sudeep@support.com',
    phone: '9002222222',
    department: 'Billing Support',
    created_date: new Date(),
  },
  {
    uid: 'AGT003',
    password: 'pass123',
    name: 'Niladri Sen',
    email: 'niladri@support.com',
    phone: '9003333333',
    department: 'Customer Service',
    created_date: new Date(),
  },
]);

db.incidents.insertMany([
  {
    issue_id: 'ISSUE001',
    customer_id: 'CUST001',
    customer_email: 'rahul@gmail.com',
    summary: 'Internet not working',
    description: 'User cannot access internet',
    severity: 'High',
    status: 'Assigned',
    assigned_to: 'AGT001',
    logged_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    modified_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    progress_notes: '[2026-03-06 10:10:00] Status changed from Assigned to In Progress: Issue currently being analyzed',
    resolution_description: null,
    resolution_date: null,
  },
  {
    issue_id: 'ISSUE002',
    customer_id: 'CUST002',
    customer_email: 'priya@gmail.com',
    summary: 'Billing error',
    description: 'Incorrect bill generated',
    severity: 'Medium',
    status: 'New',
    assigned_to: null,
    logged_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    modified_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    progress_notes: '[2026-03-06 10:00:00] Status changed from New to Assigned: Agent assigned to investigate issue',
    resolution_description: null,
    resolution_date: null,
  },
  {
    issue_id: 'ISSUE003',
    customer_id: 'CUST003',
    customer_email: 'amit@gmail.com',
    summary: 'Login problem',
    description: 'Customer cannot login',
    severity: 'High',
    status: 'In Progress',
    assigned_to: 'AGT001',
    logged_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    modified_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    progress_notes: null,
    resolution_description: null,
    resolution_date: null,
  },
  {
    issue_id: 'ISSUE004',
    customer_id: 'CUST004',
    customer_email: 'neha@gmail.com',
    summary: 'Password reset',
    description: 'User forgot password',
    severity: 'Low',
    status: 'Resolved',
    assigned_to: 'AGT003',
    logged_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    modified_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    progress_notes: 'Reset link sent and confirmed.',
    resolution_description: 'Password reset completed successfully.',
    resolution_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    issue_id: 'ISSUE005',
    customer_id: 'CUST005',
    customer_email: 'rohit@gmail.com',
    summary: 'Slow network',
    description: 'Internet speed very slow',
    severity: 'Medium',
    status: 'Assigned',
    assigned_to: 'AGT002',
    logged_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    modified_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    progress_notes: null,
    resolution_description: null,
    resolution_date: null,
  },
  {
    issue_id: 'ISSUE006',
    customer_id: 'CUST001',
    customer_email: 'rahul@gmail.com',
    summary: 'Router reboot loop',
    description: 'Router keeps rebooting every 10 minutes',
    severity: 'High',
    status: 'Closed',
    assigned_to: 'AGT001',
    logged_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    modified_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    progress_notes: 'Hardware diagnosed and replaced.',
    resolution_description: 'Router replaced and stability confirmed.',
    resolution_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    issue_id: 'ISSUE007',
    customer_id: 'CUST002',
    customer_email: 'priya@gmail.com',
    summary: 'Invoice PDF download fails',
    description: 'Download button returns 500',
    severity: 'Medium',
    status: 'Assigned',
    assigned_to: 'AGT002',
    logged_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    modified_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    progress_notes: 'Issue reproduced in production logs.',
    resolution_description: null,
    resolution_date: null,
  },
  {
    issue_id: 'ISSUE008',
    customer_id: 'CUST003',
    customer_email: 'amit@gmail.com',
    summary: 'Profile update issue',
    description: 'Unable to save profile phone number',
    severity: 'Low',
    status: 'New',
    assigned_to: null,
    logged_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    modified_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    progress_notes: null,
    resolution_description: null,
    resolution_date: null,
  },
  {
    issue_id: 'ISSUE009',
    customer_id: 'CUST004',
    customer_email: 'neha@gmail.com',
    summary: 'App crash on launch',
    description: 'Android app crashes immediately after splash screen',
    severity: 'High',
    status: 'In Progress',
    assigned_to: 'AGT003',
    logged_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    modified_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    progress_notes: 'Crash logs collected and shared with engineering.',
    resolution_description: null,
    resolution_date: null,
  },
  {
    issue_id: 'ISSUE010',
    customer_id: 'CUST005',
    customer_email: 'rohit@gmail.com',
    summary: 'Duplicate charge complaint',
    description: 'Customer reports duplicate payment deduction',
    severity: 'Medium',
    status: 'Resolved',
    assigned_to: 'AGT002',
    logged_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    modified_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    progress_notes: 'Billing team verified payment records.',
    resolution_description: 'Duplicate charge reversed and customer notified.',
    resolution_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
]);

print('Mongo seed complete.');
